title: Ciências da Computação Anhanguera
markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1

repository: http://miamarti.github.io/Ciencias-da-Computacao/
help_url: http://miamarti.github.io/Ciencias-da-Computacao/

collections:
  docs:
    output: true
